version: '3'

services:
  lambda-php-skeleton:
    image: bref/dev-env
    volumes:
      - $PWD/:/var/task
    environment:
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  bref-php:
    image: bref/php-80
    volumes:
      - $PWD/:/var/task