service: lambda-php-skeleton

provider:
    name: aws
    stage: ${opt:stage, 'dev'}
    region: ${env:AWS_DEFAULT_REGION}
    runtime: provided
    memorySize: 128 # Overwrite the default memory size. Default is 1024
    usagePlan: # Optional usage plan configuration
        quota:
            limit: 1000
            period: MONTH
        throttle:
            burstLimit: 20
            rateLimit: 10

plugins:
    - ./vendor/bref/bref

functions:
    cronjob:
        handler: lambda/cronjob.php
        description: 'Example scheduled task running with AWS lambda'
        memorySize: 128
        timeout: 5
        layers:
            - ${bref:layer.php-74}
        events:
            - schedule:
                  rate: cron(0 16 * * ? *)
                  enabled: true
    function:
        handler: lambda/function.php
        description: 'Example lambda function'
        memorySize: 128
        timeout: 5
        layers:
            - ${bref:layer.php-74}
        events:
            - sns:
                  arn: !Ref snsTriggerFunction
                  topicName: triggerFunction-${opt:stage}
    http:
        handler: lambda/http.php
        description: 'Example HTTP'
        memorySize: 128
        timeout: 5
        layers:
            - ${bref:layer.php-74-fpm}
        events:
            - httpApi:
                  method: GET
                  path: /
                  cors: true

resources:
    Resources:
        snsTriggerFunction:
            Type: AWS::SNS::Topic
            Properties:
                TopicName: triggerFunction-${opt:stage}

# Exclude files from deployment
package:
    exclude:
        - 'dev/**'
        - 'docker/**'
        - 'node_modules/**'
        - 'test/**'
        - 'tests/**'